<?php

declare(strict_types=1);

/* This file was autogenerated by spec/parser.php - Do not modify */

namespace PhpAmqpLib\Helper\Protocol;

use PhpAmqpLib\Wire\AMQPReader;
use PhpAmqpLib\Wire\AMQPWriter;

class Protocol080
{
    /**
     * @param int $version_major
     * @param int $version_minor
     * @param mixed $server_properties
     * @param string $mechanisms
     * @param string $locales
     */
    public function connectionStart(
        $version_major = 0,
        $version_minor = 8,
        $server_properties = [],
        $mechanisms = 'PLAIN',
        $locales = 'en_US'
    ): array {
        $writer = new AMQPWriter();
        $writer->write_octet($version_major);
        $writer->write_octet($version_minor);
        $writer->write_table(empty($server_properties) ? [] : $server_properties);
        $writer->write_longstr($mechanisms);
        $writer->write_longstr($locales);
        return [10, 10, $writer];
    }

    public static function connectionStartOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_table();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_longstr();
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $challenge
     */
    public function connectionSecure($challenge): array
    {
        $writer = new AMQPWriter();
        $writer->write_longstr($challenge);
        return [10, 20, $writer];
    }

    public static function connectionSecureOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longstr();
        return $response;
    }

    /**
     * @param int $channel_max
     * @param int $frame_max
     * @param int $heartbeat
     */
    public function connectionTune($channel_max = 0, $frame_max = 0, $heartbeat = 0): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($channel_max);
        $writer->write_long($frame_max);
        $writer->write_short($heartbeat);
        return [10, 30, $writer];
    }

    public static function connectionTuneOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_short();
        $response[] = $reader->read_long();
        $response[] = $reader->read_short();
        return $response;
    }

    /**
     * @param string $virtual_host
     * @param string $capabilities
     * @param bool $insist
     */
    public function connectionOpen($virtual_host = '/', $capabilities = '', $insist = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($virtual_host);
        $writer->write_shortstr($capabilities);
        $writer->write_bits([$insist]);
        return [10, 40, $writer];
    }

    public static function connectionOpenOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $host
     * @param string $known_hosts
     */
    public function connectionRedirect($host, $known_hosts = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($host);
        $writer->write_shortstr($known_hosts);
        return [10, 50, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param int $class_id
     * @param int $method_id
     */
    public function connectionClose($reply_code, $reply_text, $class_id, $method_id): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_short($class_id);
        $writer->write_short($method_id);
        return [10, 60, $writer];
    }

    public static function connectionCloseOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $out_of_band
     */
    public function channelOpen($out_of_band = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($out_of_band);
        return [20, 10, $writer];
    }

    public static function channelOpenOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param bool $active
     */
    public function channelFlow($active): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$active]);
        return [20, 20, $writer];
    }

    public static function channelFlowOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_bit();
        return $response;
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param \PhpAmqpLib\Wire\AMQPTable|array $details
     */
    public function channelAlert($reply_code, $reply_text = '', $details = []): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_table(empty($details) ? [] : $details);
        return [20, 30, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param int $class_id
     * @param int $method_id
     */
    public function channelClose($reply_code, $reply_text, $class_id, $method_id): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_short($class_id);
        $writer->write_short($method_id);
        return [20, 40, $writer];
    }

    public static function channelCloseOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $realm
     * @param bool $exclusive
     * @param bool $passive
     * @param bool $active
     * @param bool $write
     * @param bool $read
     */
    public function accessRequest(
        $realm = '/data',
        $exclusive = false,
        $passive = true,
        $active = true,
        $write = true,
        $read = true
    ): array {
        $writer = new AMQPWriter();
        $writer->write_shortstr($realm);
        $writer->write_bits([$exclusive, $passive, $active, $write, $read]);
        return [30, 10, $writer];
    }

    public static function accessRequestOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_short();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $type
     * @param bool $passive
     * @param bool $durable
     * @param bool $auto_delete
     * @param bool $internal
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function exchangeDeclare(
        $ticket = 1,
        $exchange = '',
        $type = 'direct',
        $passive = false,
        $durable = false,
        $auto_delete = false,
        $internal = false,
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($type);
        $writer->write_bits([$passive, $durable, $auto_delete, $internal, $nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [40, 10, $writer];
    }

    public static function exchangeDeclareOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param bool $if_unused
     * @param bool $nowait
     */
    public function exchangeDelete($ticket = 1, $exchange = '', $if_unused = false, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_bits([$if_unused, $nowait]);
        return [40, 20, $writer];
    }

    public static function exchangeDeleteOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $passive
     * @param bool $durable
     * @param bool $exclusive
     * @param bool $auto_delete
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueDeclare(
        $ticket = 1,
        $queue = '',
        $passive = false,
        $durable = false,
        $exclusive = false,
        $auto_delete = false,
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$passive, $durable, $exclusive, $auto_delete, $nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 10, $writer];
    }

    public static function queueDeclareOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_long();
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $exchange
     * @param string $routing_key
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueBind(
        $ticket = 1,
        $queue = '',
        $exchange = '',
        $routing_key = '',
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 20, $writer];
    }

    public static function queueBindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $nowait
     */
    public function queuePurge($ticket = 1, $queue = '', $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$nowait]);
        return [50, 30, $writer];
    }

    public static function queuePurgeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $if_unused
     * @param bool $if_empty
     * @param bool $nowait
     */
    public function queueDelete($ticket = 1, $queue = '', $if_unused = false, $if_empty = false, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$if_unused, $if_empty, $nowait]);
        return [50, 40, $writer];
    }

    public static function queueDeleteOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $exchange
     * @param string $routing_key
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueUnbind($ticket = 1, $queue = '', $exchange = '', $routing_key = '', $arguments = []): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 50, $writer];
    }

    public static function queueUnbindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $prefetch_size
     * @param int $prefetch_count
     * @param bool $global
     */
    public function basicQos($prefetch_size = 0, $prefetch_count = 0, $global = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_long($prefetch_size);
        $writer->write_short($prefetch_count);
        $writer->write_bits([$global]);
        return [60, 10, $writer];
    }

    public static function basicQosOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $consumer_tag
     * @param bool $no_local
     * @param bool $no_ack
     * @param bool $exclusive
     * @param bool $nowait
     */
    public function basicConsume(
        $ticket = 1,
        $queue = '',
        $consumer_tag = '',
        $no_local = false,
        $no_ack = false,
        $exclusive = false,
        $nowait = false
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$no_local, $no_ack, $exclusive, $nowait]);
        return [60, 20, $writer];
    }

    public static function basicConsumeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $consumer_tag
     * @param bool $nowait
     */
    public function basicCancel($consumer_tag, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$nowait]);
        return [60, 30, $writer];
    }

    public static function basicCancelOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $routing_key
     * @param bool $mandatory
     * @param bool $immediate
     */
    public function basicPublish($ticket = 1, $exchange = '', $routing_key = '', $mandatory = false, $immediate = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$mandatory, $immediate]);
        return [60, 40, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param string $exchange
     * @param string $routing_key
     */
    public function basicReturn($reply_code, $reply_text, $exchange, $routing_key): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [60, 50, $writer];
    }

    /**
     * @param string $consumer_tag
     * @param int $delivery_tag
     * @param bool $redelivered
     * @param string $exchange
     * @param string $routing_key
     */
    public function basicDeliver($consumer_tag, $delivery_tag, $redelivered, $exchange, $routing_key): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$redelivered]);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [60, 60, $writer];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $no_ack
     */
    public function basicGet($ticket = 1, $queue = '', $no_ack = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$no_ack]);
        return [60, 70, $writer];
    }

    public static function basicGetOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longlong();
        $response[] = $reader->read_bit();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_long();
        return $response;
    }

    public static function basicGetEmpty(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $delivery_tag
     * @param bool $multiple
     */
    public function basicAck($delivery_tag = 0, $multiple = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$multiple]);
        return [60, 80, $writer];
    }

    /**
     * @param int $delivery_tag
     * @param bool $requeue
     */
    public function basicReject($delivery_tag, $requeue = true): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$requeue]);
        return [60, 90, $writer];
    }

    /**
     * @param bool $requeue
     */
    public function basicRecoverAsync($requeue = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$requeue]);
        return [60, 100, $writer];
    }

    /**
     * @param bool $requeue
     */
    public function basicRecover($requeue = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$requeue]);
        return [60, 110, $writer];
    }

    public static function basicRecoverOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $prefetch_size
     * @param int $prefetch_count
     * @param bool $global
     */
    public function fileQos($prefetch_size = 0, $prefetch_count = 0, $global = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_long($prefetch_size);
        $writer->write_short($prefetch_count);
        $writer->write_bits([$global]);
        return [70, 10, $writer];
    }

    public static function fileQosOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $consumer_tag
     * @param bool $no_local
     * @param bool $no_ack
     * @param bool $exclusive
     * @param bool $nowait
     */
    public function fileConsume(
        $ticket = 1,
        $queue = '',
        $consumer_tag = '',
        $no_local = false,
        $no_ack = false,
        $exclusive = false,
        $nowait = false
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$no_local, $no_ack, $exclusive, $nowait]);
        return [70, 20, $writer];
    }

    public static function fileConsumeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $consumer_tag
     * @param bool $nowait
     */
    public function fileCancel($consumer_tag, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$nowait]);
        return [70, 30, $writer];
    }

    public static function fileCancelOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $identifier
     * @param int $content_size
     */
    public function fileOpen($identifier, $content_size): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($identifier);
        $writer->write_longlong($content_size);
        return [70, 40, $writer];
    }

    public static function fileOpenOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longlong();
        return $response;
    }

    public function fileStage(): array
    {
        $writer = new AMQPWriter();
        return [70, 50, $writer];
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $routing_key
     * @param bool $mandatory
     * @param bool $immediate
     * @param string $identifier
     */
    public function filePublish(
        $ticket = 1,
        $exchange = '',
        $routing_key = '',
        $mandatory = false,
        $immediate = false,
        $identifier = ''
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$mandatory, $immediate]);
        $writer->write_shortstr($identifier);
        return [70, 60, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param string $exchange
     * @param string $routing_key
     */
    public function fileReturn($reply_code = 200, $reply_text = '', $exchange = '', $routing_key = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [70, 70, $writer];
    }

    /**
     * @param string $consumer_tag
     * @param int $delivery_tag
     * @param bool $redelivered
     * @param string $exchange
     * @param string $routing_key
     * @param string $identifier
     */
    public function fileDeliver(
        $consumer_tag,
        $delivery_tag,
        $redelivered,
        $exchange,
        $routing_key,
        $identifier
    ): array {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$redelivered]);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_shortstr($identifier);
        return [70, 80, $writer];
    }

    /**
     * @param int $delivery_tag
     * @param bool $multiple
     */
    public function fileAck($delivery_tag = 0, $multiple = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$multiple]);
        return [70, 90, $writer];
    }

    /**
     * @param int $delivery_tag
     * @param bool $requeue
     */
    public function fileReject($delivery_tag, $requeue = true): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$requeue]);
        return [70, 100, $writer];
    }

    /**
     * @param int $prefetch_size
     * @param int $prefetch_count
     * @param int $consume_rate
     * @param bool $global
     */
    public function streamQos($prefetch_size = 0, $prefetch_count = 0, $consume_rate = 0, $global = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_long($prefetch_size);
        $writer->write_short($prefetch_count);
        $writer->write_long($consume_rate);
        $writer->write_bits([$global]);
        return [80, 10, $writer];
    }

    public static function streamQosOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $consumer_tag
     * @param bool $no_local
     * @param bool $exclusive
     * @param bool $nowait
     */
    public function streamConsume(
        $ticket = 1,
        $queue = '',
        $consumer_tag = '',
        $no_local = false,
        $exclusive = false,
        $nowait = false
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$no_local, $exclusive, $nowait]);
        return [80, 20, $writer];
    }

    public static function streamConsumeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $consumer_tag
     * @param bool $nowait
     */
    public function streamCancel($consumer_tag, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$nowait]);
        return [80, 30, $writer];
    }

    public static function streamCancelOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $routing_key
     * @param bool $mandatory
     * @param bool $immediate
     */
    public function streamPublish(
        $ticket = 1,
        $exchange = '',
        $routing_key = '',
        $mandatory = false,
        $immediate = false
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$mandatory, $immediate]);
        return [80, 40, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param string $exchange
     * @param string $routing_key
     */
    public function streamReturn($reply_code = 200, $reply_text = '', $exchange = '', $routing_key = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [80, 50, $writer];
    }

    /**
     * @param string $consumer_tag
     * @param int $delivery_tag
     * @param string $exchange
     * @param string $queue
     */
    public function streamDeliver($consumer_tag, $delivery_tag, $exchange, $queue): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_longlong($delivery_tag);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($queue);
        return [80, 60, $writer];
    }

    public function txSelect(): array
    {
        $writer = new AMQPWriter();
        return [90, 10, $writer];
    }

    public static function txSelectOk(AMQPReader $reader): array
    {
        return [];
    }

    public function txCommit(): array
    {
        $writer = new AMQPWriter();
        return [90, 20, $writer];
    }

    public static function txCommitOk(AMQPReader $reader): array
    {
        return [];
    }

    public function txRollback(): array
    {
        $writer = new AMQPWriter();
        return [90, 30, $writer];
    }

    public static function txRollbackOk(AMQPReader $reader): array
    {
        return [];
    }

    public function dtxSelect(): array
    {
        $writer = new AMQPWriter();
        return [100, 10, $writer];
    }

    public static function dtxSelectOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $dtx_identifier
     */
    public function dtxStart($dtx_identifier): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($dtx_identifier);
        return [100, 20, $writer];
    }

    public static function dtxStartOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param \PhpAmqpLib\Wire\AMQPTable|array $meta_data
     */
    public function tunnelRequest($meta_data): array
    {
        $writer = new AMQPWriter();
        $writer->write_table(empty($meta_data) ? [] : $meta_data);
        return [110, 10, $writer];
    }

    /**
     * @param int $integer_1
     * @param int $integer_2
     * @param int $integer_3
     * @param int $integer_4
     * @param int $operation
     */
    public function testInteger($integer_1, $integer_2, $integer_3, $integer_4, $operation): array
    {
        $writer = new AMQPWriter();
        $writer->write_octet($integer_1);
        $writer->write_short($integer_2);
        $writer->write_long($integer_3);
        $writer->write_longlong($integer_4);
        $writer->write_octet($operation);
        return [120, 10, $writer];
    }

    public static function testIntegerOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longlong();
        return $response;
    }

    /**
     * @param string $string_1
     * @param string $string_2
     * @param int $operation
     */
    public function testString($string_1, $string_2, $operation): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($string_1);
        $writer->write_longstr($string_2);
        $writer->write_octet($operation);
        return [120, 20, $writer];
    }

    public static function testStringOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longstr();
        return $response;
    }

    /**
     * @param \PhpAmqpLib\Wire\AMQPTable|array $table
     * @param int $integer_op
     * @param int $string_op
     */
    public function testTable($table, $integer_op, $string_op): array
    {
        $writer = new AMQPWriter();
        $writer->write_table(empty($table) ? [] : $table);
        $writer->write_octet($integer_op);
        $writer->write_octet($string_op);
        return [120, 30, $writer];
    }

    public static function testTableOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longlong();
        $response[] = $reader->read_longstr();
        return $response;
    }

    public function testContent(): array
    {
        $writer = new AMQPWriter();
        return [120, 40, $writer];
    }

    public static function testContentOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_long();
        return $response;
    }
}
