<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

namespace PhpAmqpLib\Helper\Protocol;

use PhpAmqpLib\Wire\AMQPWriter;
use PhpAmqpLib\Wire\AMQPReader;

class Protocol091
{
    /**
     * @param int $version_major
     * @param int $version_minor
     * @param mixed $server_properties
     * @param string $mechanisms
     * @param string $locales
     */
    public function connectionStart(
        $version_major = 0,
        $version_minor = 9,
        $server_properties = [],
        $mechanisms = 'PLAIN',
        $locales = 'en_US'
    ): array {
        $writer = new AMQPWriter();
        $writer->write_octet($version_major);
        $writer->write_octet($version_minor);
        $writer->write_table(empty($server_properties) ? [] : $server_properties);
        $writer->write_longstr($mechanisms);
        $writer->write_longstr($locales);
        return [10, 10, $writer];
    }

    public static function connectionStartOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_table();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_longstr();
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $challenge
     */
    public function connectionSecure($challenge): array
    {
        $writer = new AMQPWriter();
        $writer->write_longstr($challenge);
        return [10, 20, $writer];
    }

    public static function connectionSecureOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longstr();
        return $response;
    }

    /**
     * @param int $channel_max
     * @param int $frame_max
     * @param int $heartbeat
     */
    public function connectionTune($channel_max = 0, $frame_max = 0, $heartbeat = 0): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($channel_max);
        $writer->write_long($frame_max);
        $writer->write_short($heartbeat);
        return [10, 30, $writer];
    }

    public static function connectionTuneOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_short();
        $response[] = $reader->read_long();
        $response[] = $reader->read_short();
        return $response;
    }

    /**
     * @param string $virtual_host
     * @param string $capabilities
     * @param bool $insist
     */
    public function connectionOpen($virtual_host = '/', $capabilities = '', $insist = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($virtual_host);
        $writer->write_shortstr($capabilities);
        $writer->write_bits([$insist]);
        return [10, 40, $writer];
    }

    public static function connectionOpenOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param int $class_id
     * @param int $method_id
     */
    public function connectionClose($reply_code, $reply_text, $class_id, $method_id): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_short($class_id);
        $writer->write_short($method_id);
        return [10, 50, $writer];
    }

    public static function connectionCloseOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $reason
     */
    public function connectionBlocked($reason = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($reason);
        return [10, 60, $writer];
    }

    public static function connectionUnblocked(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $out_of_band
     */
    public function channelOpen($out_of_band = ''): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($out_of_band);
        return [20, 10, $writer];
    }

    public static function channelOpenOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longstr();
        return $response;
    }

    /**
     * @param bool $active
     */
    public function channelFlow($active): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$active]);
        return [20, 20, $writer];
    }

    public static function channelFlowOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_bit();
        return $response;
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param int $class_id
     * @param int $method_id
     */
    public function channelClose($reply_code, $reply_text, $class_id, $method_id): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_short($class_id);
        $writer->write_short($method_id);
        return [20, 40, $writer];
    }

    public static function channelCloseOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param string $realm
     * @param bool $exclusive
     * @param bool $passive
     * @param bool $active
     * @param bool $write
     * @param bool $read
     */
    public function accessRequest(
        $realm = '/data',
        $exclusive = false,
        $passive = true,
        $active = true,
        $write = true,
        $read = true
    ): array {
        $writer = new AMQPWriter();
        $writer->write_shortstr($realm);
        $writer->write_bits([$exclusive, $passive, $active, $write, $read]);
        return [30, 10, $writer];
    }

    public static function accessRequestOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_short();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $type
     * @param bool $passive
     * @param bool $durable
     * @param bool $auto_delete
     * @param bool $internal
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function exchangeDeclare(
        $ticket = 0,
        $exchange = '',
        $type = 'direct',
        $passive = false,
        $durable = false,
        $auto_delete = false,
        $internal = false,
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($type);
        $writer->write_bits([$passive, $durable, $auto_delete, $internal, $nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [40, 10, $writer];
    }

    public static function exchangeDeclareOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param bool $if_unused
     * @param bool $nowait
     */
    public function exchangeDelete($ticket = 0, $exchange = '', $if_unused = false, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_bits([$if_unused, $nowait]);
        return [40, 20, $writer];
    }

    public static function exchangeDeleteOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $destination
     * @param string $source
     * @param string $routing_key
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function exchangeBind(
        $ticket = 0,
        $destination = '',
        $source = '',
        $routing_key = '',
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($destination);
        $writer->write_shortstr($source);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [40, 30, $writer];
    }

    public static function exchangeBindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $destination
     * @param string $source
     * @param string $routing_key
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function exchangeUnbind(
        $ticket = 0,
        $destination = '',
        $source = '',
        $routing_key = '',
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($destination);
        $writer->write_shortstr($source);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [40, 40, $writer];
    }

    public static function exchangeUnbindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $passive
     * @param bool $durable
     * @param bool $exclusive
     * @param bool $auto_delete
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueDeclare(
        $ticket = 0,
        $queue = '',
        $passive = false,
        $durable = false,
        $exclusive = false,
        $auto_delete = false,
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$passive, $durable, $exclusive, $auto_delete, $nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 10, $writer];
    }

    public static function queueDeclareOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_long();
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $exchange
     * @param string $routing_key
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueBind(
        $ticket = 0,
        $queue = '',
        $exchange = '',
        $routing_key = '',
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 20, $writer];
    }

    public static function queueBindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $nowait
     */
    public function queuePurge($ticket = 0, $queue = '', $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$nowait]);
        return [50, 30, $writer];
    }

    public static function queuePurgeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $if_unused
     * @param bool $if_empty
     * @param bool $nowait
     */
    public function queueDelete($ticket = 0, $queue = '', $if_unused = false, $if_empty = false, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$if_unused, $if_empty, $nowait]);
        return [50, 40, $writer];
    }

    public static function queueDeleteOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_long();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $exchange
     * @param string $routing_key
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function queueUnbind($ticket = 0, $queue = '', $exchange = '', $routing_key = '', $arguments = []): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [50, 50, $writer];
    }

    public static function queueUnbindOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * Specifies QoS
     *
     * See https://www.rabbitmq.com/consumer-prefetch.html#overview for details
     *
     * @param int $prefetch_size Default is 0 (Alias for unlimited)
     * @param int $prefetch_count Default is 0 (Alias for unlimited)
     * @param bool $global Default is false, prefetch size and count are applied to each channel consumer separately
     */
    public function basicQos($prefetch_size = 0, $prefetch_count = 0, $global = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_long($prefetch_size);
        $writer->write_short($prefetch_count);
        $writer->write_bits([$global]);
        return [60, 10, $writer];
    }

    public static function basicQosOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param string $consumer_tag
     * @param bool $no_local
     * @param bool $no_ack
     * @param bool $exclusive
     * @param bool $nowait
     * @param \PhpAmqpLib\Wire\AMQPTable|array $arguments
     */
    public function basicConsume(
        $ticket = 0,
        $queue = '',
        $consumer_tag = '',
        $no_local = false,
        $no_ack = false,
        $exclusive = false,
        $nowait = false,
        $arguments = []
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$no_local, $no_ack, $exclusive, $nowait]);
        $writer->write_table(empty($arguments) ? [] : $arguments);
        return [60, 20, $writer];
    }

    public static function basicConsumeOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param string $consumer_tag
     * @param bool $nowait
     */
    public function basicCancel($consumer_tag, $nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_bits([$nowait]);
        return [60, 30, $writer];
    }

    public static function basicCancelOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $ticket
     * @param string $exchange
     * @param string $routing_key
     * @param bool $mandatory
     * @param bool $immediate
     */
    public function basicPublish(
        $ticket = 0,
        $exchange = '',
        $routing_key = '',
        $mandatory = false,
        $immediate = false
    ): array {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        $writer->write_bits([$mandatory, $immediate]);
        return [60, 40, $writer];
    }

    /**
     * @param int $reply_code
     * @param string $reply_text
     * @param string $exchange
     * @param string $routing_key
     */
    public function basicReturn($reply_code, $reply_text, $exchange, $routing_key): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($reply_code);
        $writer->write_shortstr($reply_text);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [60, 50, $writer];
    }

    /**
     * @param string $consumer_tag
     * @param int $delivery_tag
     * @param bool $redelivered
     * @param string $exchange
     * @param string $routing_key
     */
    public function basicDeliver($consumer_tag, $delivery_tag, $redelivered, $exchange, $routing_key): array
    {
        $writer = new AMQPWriter();
        $writer->write_shortstr($consumer_tag);
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$redelivered]);
        $writer->write_shortstr($exchange);
        $writer->write_shortstr($routing_key);
        return [60, 60, $writer];
    }

    /**
     * @param int $ticket
     * @param string $queue
     * @param bool $no_ack
     */
    public function basicGet($ticket = 0, $queue = '', $no_ack = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_short($ticket);
        $writer->write_shortstr($queue);
        $writer->write_bits([$no_ack]);
        return [60, 70, $writer];
    }

    public static function basicGetOk(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_longlong();
        $response[] = $reader->read_bit();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_shortstr();
        $response[] = $reader->read_long();
        return $response;
    }

    public static function basicGetEmpty(AMQPReader $reader): array
    {
        $response = [];
        $response[] = $reader->read_shortstr();
        return $response;
    }

    /**
     * @param int $delivery_tag
     * @param bool $multiple
     */
    public function basicAck($delivery_tag = 0, $multiple = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$multiple]);
        return [60, 80, $writer];
    }

    /**
     * @param int $delivery_tag
     * @param bool $requeue
     */
    public function basicReject($delivery_tag, $requeue = true): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$requeue]);
        return [60, 90, $writer];
    }

    /**
     * @param bool $requeue
     */
    public function basicRecoverAsync($requeue = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$requeue]);
        return [60, 100, $writer];
    }

    /**
     * @param bool $requeue
     */
    public function basicRecover($requeue = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$requeue]);
        return [60, 110, $writer];
    }

    public static function basicRecoverOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param int $delivery_tag
     * @param bool $multiple
     * @param bool $requeue
     */
    public function basicNack($delivery_tag = 0, $multiple = false, $requeue = true): array
    {
        $writer = new AMQPWriter();
        $writer->write_longlong($delivery_tag);
        $writer->write_bits([$multiple, $requeue]);
        return [60, 120, $writer];
    }

    public function txSelect(): array
    {
        $writer = new AMQPWriter();
        return [90, 10, $writer];
    }

    public static function txSelectOk(AMQPReader $reader): array
    {
        return [];
    }

    public function txCommit(): array
    {
        $writer = new AMQPWriter();
        return [90, 20, $writer];
    }

    public static function txCommitOk(AMQPReader $reader): array
    {
        return [];
    }

    public function txRollback(): array
    {
        $writer = new AMQPWriter();
        return [90, 30, $writer];
    }

    public static function txRollbackOk(AMQPReader $reader): array
    {
        return [];
    }

    /**
     * @param bool $nowait
     */
    public function confirmSelect($nowait = false): array
    {
        $writer = new AMQPWriter();
        $writer->write_bits([$nowait]);
        return [85, 10, $writer];
    }

    public static function confirmSelectOk(AMQPReader $reader): array
    {
        return [];
    }
}
